### ISSUE TITLE
提个问题

### ISSUE THREAD

**Issue by lisongting** [marktony/FanfouHandpick#1]
Tonny你好，请问你是使用什么方式给APK签名的？我使用Android Studio中生成的keystore给我的APK签名后，发布在fir.im上，下载下来安装不上，手机中提示我“找不到签名证书”，安装失败。。。

**Comment by TonnyL** [comment]
不要用as自带的debug keystore签名。自己新建一个即可。

**Comment by lisongting** [comment]
怎样自己新建一个？有没有相关的教程或链接之类的？

**Comment by TonnyL** [comment]
http://www.jianshu.com/p/f6b71cd44696 中间有讲怎样新建keystore的。

**Comment by lisongting** [comment]
那就奇怪了，我也是用这种方法对APK签名的，发布在fir.im上之后，下载后，手机中还是提示我“找不到签名证书”。

**Comment by TonnyL** [comment]
Google吧， 我没有遇到过这样的问题。

update：你可以尝试新建一个项目，然后用自己的key签名，看看是不是同样的问题。如果是，说明是签名方法不对或者是key有问题，不过不是，应该就是项目里面有文件出错之类或者和kt有冲突？
